baseURL                   = "https://example.com"
builddrafts                = false
languageCode               = "De-de"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = false
summaryLength              = 50
Paginate                   = 5

theme                      = "AllinOne"
title                      = "Chrisina Unterwegs"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "WoMo-Blog"
    weight                 = -120
    identifier             = "womo"
    url                    = "womo/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/CIU.png"               # from static/
  avatar                   = "img/profile.png"           # path to image in static dir e.g img/avatar.png 
  author                   = "Chrisina Unterwegs"
  description              = ["Unterwegs zu Zweit.", "Mit WoMo, Rad, im Wasser und zu Fuß", "Für alles was uns bewegt"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Herzlich Willkommen bei unserem WoMo-Blog und Tagebuch"
  welcome_word             = "~ Hier geht es um unsere Touren mit dem Wohnmobil, mit dem Rad, laufend oder schwimmend oder was uns sonst noch so bewegt ~"

  latestpostscount         = 6                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "2 Jan, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = true                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "ch.ketzer@gmail.com"
  github                   = "//github.com/CKXD"
  # linkedin                 = "//linkedin.com/in/you"
  facebook                 = "//facebook.com/christoph.ketzer.75"
  #googleplus               = "//google.com/you"
  #twitter                  = "//twitter.com/you" 
  #px500                    = "//px500"
  instagram                = "//instagram.com/pxpress"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    